### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [onqtam/doctest#103]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by onqtam** [comment]
It's on my to-do list... I'll have to get familiar with conan even though I ain't planning on using it yet

**Comment by mmha** [comment]
I have already created [a Conan package](https://bintray.com/mmha/conan/doctest%3Ammha). Feel free to adopt it.

**Comment by ZaMaZaN4iK** [comment]
@mmha do you want to push your package to Bincrafters repo?

**Comment by mmha** [comment]
I can do that.

**Comment by onqtam** [comment]
So there is [this](https://github.com/bincrafters/conan-doctest) - I'm not sure who is maintaining it - is that you, @mmha ? In any case I'm glad someone else has done this for the project! I'll add a link to that package in the ```build-systems``` part of the documentation.

**Comment by mmha** [comment]
I wrote the initial recipe, but I don't maintain it. That would probably be @ZaMaZaN4iK, @solvingj or someone else who is part of Bincrafters.

**Comment by onqtam** [comment]
here are a bunch of links to checkout when I get to this:

- https://github.com/bincrafters/conan-doctest
- https://github.com/uilianries/conan-catch
- https://github.com/philsquared/Catch/pull/938
- https://stackoverflow.com/questions/40311363/conan-io-header-only-package
- https://github.com/conan-io/docs/issues/67
- https://github.com/agauniyal/rang
- https://github.com/conan-io/conan/issues/324
- auto upload to bintray: https://github.com/Morwenn/cpp-sort/blob/57aaff88e7b135b07ebf9362435160b905f41e3d/.travis.yml#L91

**Comment by onqtam** [comment]
@solvingj

So I've gathered some links here to read about conan but since I'm not using it yet and this seems to get updated by people:
https://github.com/bincrafters/conan-doctest

And in the spirit of this talk: [CppCon 2018: Robert Schumacher “Don't package your libraries, write packagable libraries!”](https://www.youtube.com/watch?v=sBP17HQAQjk)

Is it OK for me to close this issue and point to ```bincrafters/conan-doctest``` in the docs?

I might also start submitting PRs for new releases to that repository (based on the previous PRs) but I wouldn't feel comfortable maintaining a package repo without understanding conan (and it isn't the only package manager out there...)

**Comment by solvingj** [comment]
Yes, thats all correct. Go ahead.
