### ISSUE TITLE
Add an exception translation mechanism + the ability for users to extend it with custom exception types

### ISSUE THREAD

**Issue by RaviGaddipati** [onqtam/doctest#12]
In some cases a test will fail because an exception is thrown. Right now it just says
"TEST CASE FAILED! (threw exception)"
It would be very helpful if it says what exception is thrown and the message.

**Comment by onqtam** [comment]
this is planned - also the user will be able to extend the reporting by teaching the framework about custom exception types.

**Comment by gaddra** [comment]
Great, loving the framework so far!

**Comment by arximboldi** [comment]
Related: I would like to prevent Doctest from catching the exception alltogether, so the program crashes and the backtrace is shown directly in the debugger.

**Comment by onqtam** [comment]
@arximboldi I might add a configuration identifier for this

**Comment by arximboldi** [comment]
Makes sense, thanks!

**Comment by onqtam** [comment]
This should be done in the dev branch - docs also in the dev branch!

**Comment by onqtam** [comment]
@arximboldi do you think that using [**DOCTEST_CONFIG_NO_EXCEPTIONS**](https://github.com/onqtam/doctest/blob/master/doc/markdown/configuration.md#doctest_config_no_exceptions) will be sufficient for your needs? it's already in the library and I don't want to complicate matters any further with more configuration options...

**Comment by arximboldi** [comment]
Aha! no, but `DOCTEST_CONFIG_NO_TRY_CATCH_IN_ASSERTS` which I found in the same document is enough for me indeed. Sorry I missed that and thanks!

**Comment by onqtam** [comment]
@arximboldi but using only ```DOCTEST_CONFIG_NO_TRY_CATCH_IN_ASSERTS``` will still result in exceptions thrown from a test case (or assert evaluation) being caught by the test runner and I don't think there will be a backtrace in that case...

**Comment by arximboldi** [comment]
Oh I missed that. I will try the other one then. I wonder if that will also make tests that check that an exception is thrown fail? But I guess those are just disabled, which is fine most of the time. This may not cover the case where you have a test checking an exception, an except different type is thrown, and you want to get the backtrace of where that comes from. Also, it would be nice to not have to recompile to do this... But all this is icing on the cake, I think this is good all for now.

**Comment by onqtam** [comment]
@arximboldi When using ```DOCTEST_CONFIG_NO_EXCEPTIONS``` the ```REQUIRE``` asserts and asserts that deal with exceptions (```xxx_THROWS``` / ```xxx_THROWS_AS``` / ```xxx_NOTHROW```) are gone - meaning that using them will result in a compilation error. Thats what [**DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS**](https://github.com/onqtam/doctest/blob/master/doc/markdown/configuration.md#doctest_config_no_exceptions_but_with_all_asserts) is for - it makes ```REQUIRE``` act like ```CHECK``` and the exception macros are turned into a no-op.

I'm not sure that introducing a new identifier to circumvent catching exceptions in the test runner is actually even possible without disabling other functionality - ```REQUIRE``` macros throw an exception to terminate the current test case (unlike ```CHECK```). I could have a try/catch only for ```doctest::detail::TestFailureException``` - and if I don't catch it there (but instead end up in the default ```(...)``` catch clause) I could just rethrow the exception so the program crashes - but in that case I'm not sure what you'll get in the backtrace - the point of rethrowing or the point of the original exception...

If you test this in a simple program and get the full backtrace even after rethrowing from a lower frame in the callstack then I might add a separate identifier - otherwise I'd advice using ```DOCTEST_CONFIG_NO_EXCEPTIONS```.
