### ISSUE TITLE
GCC 5.3.1 Compiler warning: sign compare

### ISSUE THREAD

**Issue by rph-pl** [onqtam/doctest#16]
Compiler:
`g++ (Debian 5.3.1-21) 5.3.1 20160528`

Code:
```
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest/doctest.h"

#include <map>

TEST_CASE("x")
{
	std::map<int, int> m;
	CHECK(m.size() == 0);
}
```

Command line (unimportant flags like include paths removed):
```
/usr/bin/c++ -std=c++14 -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -Wcast-align
-Woverloaded-virtual -g -fprofile-arcs -ftest-coverage -fno-omit-frame-pointer -O0 
-std=gnu++14
-o CMakeFiles/x.dir/tests/x.cpp.o
```

Result (full paths removed):
```
In file included from /somewhere/tests/x.cpp:2:0:
/somewhere/tests/doctest/doctest.h: In instantiation of ‘typename doctest::detail::enable_if<(doctest::detail::can_use_op<T>::value || doctest::detail::can_use_op<R>::value), bool>::type doctest::detail::eq(const L&, const R&) [with L = long unsigned int; R = int; typename doctest::detail::enable_if<(doctest::detail::can_use_op<T>::value || doctest::detail::can_use_op<R>::value), bool>::type = bool]’:
/somewhere/tests/doctest/doctest.h:593:82:   required from ‘doctest::detail::Result doctest::detail::Expression_lhs<L>::operator==(const R&) [with R = int; L = const long unsigned int&]’
/somewhere/tests/x.cpp:9:2:   required from here
/somewhere/tests/doctest/doctest.h:557:127: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  || can_use_op<R>::value, bool>::type eq (const L& lhs, const R& rhs) { return lhs == rhs; }
                                                                                    ^
```

**Comment by martinmoene** [comment]
Well the compiler is right isn't it? Using `m.size() == 0u` obviates the warning.

**Comment by onqtam** [comment]
well... I don't get a warning for ```if(m.size() == 0)``` and also Catch doesn't produce a warning for ```CHECK(m.size() == 0)``` so I should look into this...

**Comment by martinmoene** [comment]
With GNU 5.2.0 on Windows I also get the warning for `m.size() == 0`.

**Comment by martinmoene** [comment]
Catch actively [suppresses signed/unsigned mismatch](https://github.com/philsquared/Catch/blob/master/single_include/catch.hpp#L1287) for the expression decomposer.

**Comment by martinmoene** [comment]
See [// This level of indirection allows us to specialise for integer types to avoid signed/ unsigned warnings](https://github.com/philsquared/Catch/blob/master/single_include/catch.hpp#L1367).

**Comment by onqtam** [comment]
So I asked [these](http://stackoverflow.com/questions/39106893) 2 [questions](http://stackoverflow.com/questions/39075223) on SO and didn't get the nice explanation I was hoping for.

Atleast I have a conclusion: ```if(vec.size() == 0)``` does not produce a warning, but ```CHECK(vec.size() == 0)``` does - and the reason is that I bind the 2 values to const references in the expression decomposing template machinery.

I don't like the way Catch handles this in gcc/clang - all those templates and specializations must have a compile time performance overhead.

The way I've chosen is to disable the few relevant warnings in the templated code, and the user will be able to remove these warning suppressions with the ```DOCTEST_CONFIG_NO_COMPARISON_WARNING_SUPPRESSION``` identifier.
