### ISSUE TITLE
Print vector content.

### ISSUE THREAD

**Issue by slepasteur** [onqtam/doctest#170]
## Description
I am trying to print std::vector content on failure.
E.g.:
`REQUIRE(std::vector<int>{1} == std::vector<int>{1,2});`

Should produce to following output.
```
FATAL ERROR: REQUIRE( std::vector<int>{1} == std::vector<int>{1,2} ) is NOT correct!
  values: REQUIRE( [ 1 ] == [ 1 2 ] )
```
Here is my attempt:
```c++
namespace doctest {
template <typename T>
struct StringMaker<std::vector<T>>
{
    static String convert(const std::vector<T>& vec)
    {
        std::ostringstream oss;
        oss << "[ ";
        std::copy(vec.begin(), vec.end(), std::ostream_iterator<T>(oss, " "));
        oss << "]";
        return oss.str().c_str();
    }
};
} // namespace doctest
```
It works well at first but as soon as I add more translation units with more tests it starts failing and printing the default way:
```
FATAL ERROR: REQUIRE( std::vector<int>{1} == std::vector<int>{1,2} ) is NOT correct!
  values: REQUIRE( {?} == {?} )
```

### Steps to reproduce
It is kind of hard to reproduce as the output is shown only on failure and it keeps failing after some time.

### Extra information
* doctest version: **v2.0.1**
* Operating System: **Archlinux**
* Compiler+version: **clang 7.0.0 / gcc 8.2.1**

**Comment by onqtam** [comment]
Is the specialization of ```StringMaker<std::vector<T>>``` visible in all translation units? It should be - not just in one of them. Perhaps you can make a proxy header for doctest called ```doctest_proxy.h``` and have the following:

```c++
#pragma once
#include <doctest.h>

// StringMaker<std::vector<T>>
```

Perhaps I should edit the documentation if this is the problem (the specialization being present in only one of the translation units) - this might be due to ODR.

**Comment by slepasteur** [comment]
That was indeed the problem. Thank-you.

**Comment by u3shit** [comment]
Should I suggest some documentation changes wrt this issue? I've spent numerous hours trying to figure out why my custom stringification functions seem to randomly work in some files but not in others (well, I learned that you can do ODR violations with function overloads and template specializations, so it wasn't a completely wasted time, but well...).
I think the documentation should mention that if there is a specialzation in one translation unit, but on in the other and in the other you print the same type of variable, that's an ODR violation. And maybe some suggestions how to avoid it, like the wrapper header above (but it's not perfect either because a) that would force you to include a bunch of stl headers even in files you don't need them and b) won't work if you have exteral code that happen to use doctest). For your own types, you could avoid this issue by making sure to always declare the toString function in the header, next to the class and not in random c++ files. (Incidentally, can we forward declare classes from doctest? Like `namespace doctest { class String; }`, I'd rather not pull in the whole doctest header just for that in my headers.)
