### ISSUE TITLE
Add CMake test support as catch_discover_tests() in Catch2

### ISSUE THREAD

**Issue by ncihnegn** [onqtam/doctest#171]
With catch_discover_tests(), testcase names can be shown in 'make test'.

**Comment by onqtam** [comment]
I'll see what can be done about this but no timeframe can be promised.

**Comment by RedDwarf69** [comment]
@ncihnegn @DPD85 do you want to try how well https://github.com/onqtam/doctest/pull/236 covers your needs?

**Comment by onqtam** [comment]
@RedDwarf69 Glad to see someone else took the initiative for this work! I'm not sure when I'll get to reviewing it but since there is interest I guess it will eventually end up merged.

One observation I have is that often there are PRs and issues raised against Catch for this functionality so I hope it won't be just me maintaining it in the future.

**Comment by RedDwarf69** [comment]
> One observation I have is that often there are PRs and issues raised against Catch for this functionality so I hope it won't be just me maintaining it in the future.

Honestly, I can't tell you "don't worry, I will take care of them". I am not that proficient with cmake and I'm short on free time.
But I'm not going to say "not my problem" either. If any bug is raised feel free to poke me and I will do my best.

**Comment by onqtam** [comment]
closing - this has been added here: https://github.com/onqtam/doctest/blob/master/scripts/cmake/doctest.cmake
