### ISSUE TITLE
Remove INFO() limitation for using only lvalues and no rvalues

### ISSUE THREAD

**Issue by DaanDeMeyer** [onqtam/doctest#269]
reproc has a function `reproc_strerror` that takes a `REPROC_ERROR` functions and converts it into a string representation. Ideally, I could do something like `INFO(reproc_strerror(error));` in order to print a string representation of the error that occurred when a test case fails.

I did not find a way to accomplish this since `INFO` doesn't work with rvalue references. An initial approach to implementing this could be to capture the passed expression in a lambda and calling it when a test case fails and printing the output.

It might be possible to store a lambda like follows in `ContextScope` (which would become a templated class):

```c++
#define DOCTEST_INFO(expression) \
auto DOCTEST_ANONYMOUS(_DOCTEST_CAPTURE_) = \
  make_context_scope([](std::ostream *os) { return os << expression; })
```

and call it when an error occurs. From what I can see from the documentation of `INFO`, this should be backwards compatible if it works.

I'm willing to try implementing this but I wanted to touch the idea off to see if I'm not missing any obvious constraints that prevent implementation of this solution.

**Comment by DaanDeMeyer** [comment]
Making ContextScope a templated class probably won't work as it inherits from a virtual base class. We could add something like LLVM's [function_ref](https://llvm.org/doxygen/STLExtras_8h_source.html#l00119) that type erases lambda's and store that in `ContextScope` instead.

`DOCTEST_INFO` would then look as follows:

```cpp
#define DOCTEST_INFO(expression) \
auto DOCTEST_ANONYMOUS(_DOCTEST_CAPTURE_) = [&](std::ostream *os) { 
  return os << expression; 
}
doctest::detail::ContextScope DOCTEST_ANONYMOUS(_DOCTEST_CAPTURE_)(lambda)
```

Although I'm not entirely sure how we can access the name of the anonymous lambda we just declared so we can pass it to `ContextScope`.

**Comment by onqtam** [comment]
The usual way to fix this limitation is to just make a local lvalue in the function before calling INFO(), which I admit isn't ideal. I wrote the ```DOCTEST_TO_LVALUE(...)``` helper macro which could be used in the INFO() call but it requires C++14 and is just ugly.

I kind of regret the over-engineering around logging - this rvalue restriction is because of an optimization to avoid allocations and use the stack space when no assert fails all in the name of runtime performance for logging in hot loops... In reality this would matter only in loops with millions of iterations... I also wrote it before moving to C++11 - your lambda idea would work!

I don't see a problem making ContextScope a template class just because it's inheriting from a base class - that's the case with ```template <typename T> struct Capture : public ICapture```. To get the name of the lambda you would need 1 more indirection in the macros.

I actually sketched it and it works! Here it is:

```c++
// here just so the snippet can be in a .cpp where the test runner isn't visible
namespace doctest { namespace detail {
extern thread_local std::vector<IContextScope*> g_infoContexts;
}}

template<typename L>
struct ContextScope2 : public doctest::IContextScope {
    const L& _lambda;

    ContextScope2(const L& lambda)
        : _lambda(lambda) {
        doctest::detail::g_infoContexts.push_back(this);
    }

    ~ContextScope2() {
        if(std::uncaught_exception()) {
            // ...
        }
        doctest::detail::g_infoContexts.pop_back();
    }

    void stringify(std::ostream* s) const { _lambda(s); }
};

#define NEW_INFO(expr) NEW_INFO_IMPL(DOCTEST_ANONYMOUS(_DOCTEST_CAPTURE_), DOCTEST_ANONYMOUS(_DOCTEST_MB_), expr)

#define NEW_INFO_IMPL(lambda_name, mb_name, expr) \
    auto lambda = [&](std::ostream* s) { \
        doctest::detail::MessageBuilder mb_name(__FILE__, __LINE__, doctest::assertType::is_warn); \
        mb_name.m_stream = s; \
        mb_name << expr; \
    }; \
    ContextScope2<decltype(lambda)> DOCTEST_ANONYMOUS(_DOCTEST_CAPTURE_)(lambda)

TEST_CASE("") {
    int a = 5;

    NEW_INFO(a << a + 5 << 6 + 12);

    CHECK(a == 6);
}
```

This way there would be no allocation and the compiler would be generating the references to everything being logged instead of doctest. I use the ```MessageBuilder``` class just to reuse it's ```operator<<``` which in turn calls ```doctest::detail::toStream```.

This way we could remove the broken ```DOCTEST_TO_LVALUE``` and the ```ContextBuilder``` class along with all the chunks and captures inside of it - huge thanks for thinking of this lambda approach! This has been both overly-complicated, ugly and restrictive in terms of usage. If you want you could make the PR or maybe I could do it in a week or two :)

**Comment by DaanDeMeyer** [comment]
I'll try and turn this into a PR.

**Comment by DaanDeMeyer** [comment]
One problem is that because `ContextScope` is now templated and implemented in doctest_fwd, implementation details are leaking into doctest_fwd which requires including headers such as sstream and vector. I'm pretty sure we don't want to do it because of the effect on compilation times.

**Comment by DaanDeMeyer** [comment]
Actually, if I delegate the destructor implementation to a separate function I might be able to avoid implementation details leaking. Will report back after trying

**Comment by onqtam** [comment]
indeed - 2 separate functions (for the ctor and dtor bodies) accepting the ```this``` pointer through a ```doctest::IContextScope*``` argument.
