### ISSUE TITLE
Compile time awful slow with Visual Studio with optimization 

### ISSUE THREAD

**Issue by Frankyboy100880** [onqtam/doctest#29]
Today I tried to migrate a bunch of legacy tests to doctest. I have to say that I was really satisfied with the outcome and the neat usage of this excellent testing framework. Migration made it necessary to compile hundreds of cpp files.

Firstly, I build the debug version of my tests and the compilation time taking 55s was very short considering the amount of tests I had to compile.

Secondly I build the release version of my library and the compilation really took ages. After 487s the compilation was finished. 

After I used the compilation switches /Od /Ob0 instead of /O2 and /Ob2  the compilation speed up to amazing 43s. Unfortunately, the Executable became slow.

I'm wondering what I did wrong?

**Comment by onqtam** [comment]
you have done nothing wrong - I've had the same problem with VS 2010/2012 with optimized build taking 15-20 times more time than the debug build.

I'm not aware if this is still a problem with VS 2015, but for 2010/2012 the optimizer bogs down the compilation time when there are a lot of ```if``` statements inside a function - and it was getting exponentially worse - 1 function with 100 ```do {} while(false);``` (because that's how you write proper macros - wrapped in such a thing) and some ```if()``` statements in the loop with some code in them got 50 times slower when I made them 1000.

Other compilers such as gcc/clang don't have this problem.

In version 1.1 the macros (such as ```CHECK```) will make less code bloat - less branches and variables in them - but it will still be slow in such cases with MSVC with optimizations.

I'd imagine Catch would suffer from the same problem as well.

A workaround would be splitting up huge ```TEST_CASE```s with many asserts in them into multiple test cases.

**Comment by Frankyboy100880** [comment]
Many thanks for the fast reply! :+1:  

I just wanted to add that my company uses VS 2014. I also ported all legacy tests to Catch and there was no such dramatic speed loss. 

Maybe the next compiler would fix the issue.

**Comment by onqtam** [comment]
So I'm about to release version 1.1.

I did quite a lot to improve compile times - see my last post in [this issue](https://github.com/onqtam/doctest/issues/14).

Let me know what you think!
