### ISSUE TITLE
Add clearFilters() to doctest::Context

### ISSUE THREAD

**Issue by gunterfuchs** [onqtam/doctest#33]
I just wanted to let you know that doctest works great for me running on an Analog Devices ADSP21479 SHARC MCU. For that to work I had to add this macro to my build: DOCTEST_CONFIG_COLORS_NONE and _LIBCPP_VERSION.

Since I am running the tests menu driven (The Analog Devices Eclipse based CrossCore Embedded Studio 2.3.0 allows printf / scanf through the Eclipse Console.) I also created my own main function (DOCTEST_CONFIG_IMPLEMENT). Because doctest is not geared towards menu driven test I added one function to the code which allows me to run only one test the user has chosen from the menu. If you like to incorporate it into the next version, please go ahead. The function just clears the filter vectors.

BTW, it takes a few seconds to compile doctest under the Analog Devices compiler (_ADI_COMPILER) on my decently fast Windows 7 PC.

Thanks for the great work,

Günter Fuchs
gfuchs@gmail.com

[doctest.txt](https://github.com/onqtam/doctest/files/466068/doctest.txt)

**Comment by onqtam** [comment]
about the long compilation times - the source file where doctest gets implemented is always slow.
But source files that only use doctest and many assertions - compile time performance will be improved quite a lot with the upcoming 1.1 release.

about ```_LIBCPP_VERSION``` - weird - I do ```#include <ciso646>``` for clang in order to get ```_LIBCPP_VERSION ``` defined so I can detect if clang is using libstdc++ (from g++) or libc++.

Including any system header under clang should result in ```_LIBCPP_VERSION``` being defined if libc++ is used

Is the ADI compiler based on clang? or g++? If it is g++ then defining ```DOCTEST_CONFIG_USE_IOSFWD``` would be better than ```_LIBCPP_VERSION```. 

about the filter clearing feature - yes, I will add it - it seems useful.

Thanks for using the library!

**Comment by gunterfuchs** [comment]
Hi Viktor,

thanks for your advice about using DOCTEST_CONFIG_USE_IOSFWD instead of _LIBCPP_VERSION. That worked.

A time stamping feature when logging would be nice using time.h for example.

Best wishes,

Günter

**Comment by onqtam** [comment]
integration with time stuff is [planned in the roadmap](https://github.com/onqtam/doctest/blob/dev/doc/markdown/roadmap.md) :)

**Comment by onqtam** [comment]
Actually can you post me the error message when not using ```DOCTEST_CONFIG_USE_IOSFWD``` so I can put an entry in the FAQ about it?

**Comment by gunterfuchs** [comment]
The compiler stops at 100 errors. I have attached the build output.
[notesDoctest.txt](https://github.com/onqtam/doctest/files/483301/notesDoctest.txt)
