### ISSUE TITLE
Parametric test cases?

### ISSUE THREAD

**Issue by akrzemi1** [onqtam/doctest#38]
I cannot figure out if this framework supports or plans to support _parametric_ test cases, where I define a test parametrized by some value, and then instantiate a number of sibling tests with different values; or I define a test parametrized by a type (like a template) and then instantiate a number of sibling test cases using a different type.

Frameworks like Gtest or Boost.Test support them. For reference see:
1. http://www.boost.org/doc/libs/1_61_0/libs/test/doc/html/boost_test/tests_organization/test_cases/test_case_generation.html
2. http://www.boost.org/doc/libs/1_61_0/libs/test/doc/html/boost_test/tests_organization/test_cases/test_organization_templates.html#ref_BOOST_TEST_CASE_TEMPLATE
3. https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#value-parameterized-tests
4. https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#typed-tests

Can we expect a similar functionality in this library?

**Comment by onqtam** [comment]
It is in the [roadmap](https://github.com/onqtam/doctest/blob/master/doc/markdown/roadmap.md) so yes, most probably - but no date can be promised :)

**Comment by akrzemi1** [comment]
What is this feature called in the roadmap?

**Comment by h-2** [comment]
Typed tests are really important and would also be a big plus over Catch which only supports value parametrization and not typed. Without typed tests people still have to use Boost.Test and Gtest althouth they are really "old".

**Comment by onqtam** [comment]
I'll give this a higher priority.

**Comment by onqtam** [comment]
I just implemented templated test cases in the dev branch - checkout the docs [here](https://github.com/onqtam/doctest/blob/dev/doc/markdown/parameterized-tests.md) and try the feature! **Any** feedback is welcome.

Value parameterization is a different story... Typed tests were easy (not really... C++98, etc.) because I could just copy the interface of other libraries. However I feel that value parameterization is potentially a much broader topic - I'm not sure what they should look like... I haven't done my research yet :D

I need feedback on this:
- what do you think value-parameterized tests should look like?
- how is data driven testing supported by [Catch](https://github.com/philsquared/Catch) - is it done with ```SECTION()``` and logging with ```INFO()```? If that is the case doctest can do the same - my support for ```INFO()``` is in the dev branch and has far superior runtime performance - read about it [here](https://github.com/onqtam/doctest/blob/dev/doc/markdown/logging.md)
- has anyone tried the generators feature of [Catch](https://github.com/philsquared/Catch)? I cant find documentation on it... Is it postponed for Catch 2? Is that what you meant by saying that it supports value parametrization?
- what about property based testing - does doctest need to implement value-parameterization at all or can it just interop with such a library?
    - [rapidcheck](https://github.com/emil-e/rapidcheck)
    - [autocheck](https://github.com/thejohnfreeman/autocheck)
    - [CppQuickCheck](https://github.com/grogers0/CppQuickCheck)

**Comment by onqtam** [comment]
I'm renaming this issue so it's only for templated test cases and I'm closing it so it ends up in the generated changelog when I release version 1.2 in a few days.

I'll make a new issue in the future about value-parameterized tests and will link to it here.

**Comment by onqtam** [comment]
I just pushed an update to the docs in the dev branch on how to emulate value parameterization easily - [check it out](https://github.com/onqtam/doctest/blob/dev/doc/markdown/parameterized-tests.md) - search for ```DOCTEST_VALUE_PARAMETERIZED_DATA```
