### ISSUE TITLE
Test suites can't have identical names

### ISSUE THREAD

**Issue by FSund** [onqtam/doctest#40]
I recently ran into a problem while compiling, and it turned out it was caused by having multiple TEST_SUITEs with the same name. I kept getting compilation errors like this:  

    mysubclass.o: In function `DOCTEST_ANON_FOR_SEMICOLON_3()':
    mysubclass.cpp:(.text+0x0): multiple definition of `DOCTEST_ANON_FOR_SEMICOLON_3()'
    myclass.o:myclass.cpp:(.text+0x370): first defined here

<del>I now know that TEST_SUITEs need to be uniquely defined by design, but I had to investigate the documentation to realize this.  

<del>So the biggest issue is that the compilation errors aren't really helpful for figuring out the cause of the errors. Would it be possible to add some functionality that warns against multiply defined TEST_SUITEs?

**Comment by FSund** [comment]
Hmm... After further investigation, it seems like my errors were caused by something else.

**Comment by onqtam** [comment]
Weird. The strings passed to both ```TEST_CASE()``` and ```TEST_SUITE()``` need not be unique.

Test cases can have the same name - it's up to the user. Also if a test is written in a header (which the framework supports) - it is bound to end up in multiple source files - but it will be registered only once - not because of it's name but because of where it was written (based on ```__FILE__``` and ```__LINE__```).

Test cases in multiple source files may be in the same test suite by using ```TEST_SUITE("the same string")``` before the test cases - with the same string for the test suite - like this:


```c++
// a.cpp
TEST_SUITE("math");

TEST_CASE("") { /* some math stuff */ }
```

```c++
// b.cpp
TEST_SUITE("math");

TEST_CASE("") { /* some math stuff */ }
```

As far as the linker error - so weird - that's the last thing I expected to fail. To force the ```;``` semicolon after the ```TEST_SUITE()``` macro I add a dummy forward declaration of a function at the end - like this: ```void DOCTEST_ANONYMOUS(DOCTEST_ANON_FOR_SEMICOLON_)()```

If you have tried to add a function body after the test suite macro - I would imagine that would lead to errors - like this:

```c++
TEST_SUITE("the ts") { // <<<< THIS IS BAD - not intended for such use - might lead to errors
    // asserts...
}
```

The following case might lead to linker errors if the same thing is done in multiple source files.

The thing is that when you "declare" a test suite with ```TEST_SUITE("some string");``` you actually push ```some string``` as the test suite name for the test cases that follow in the current source file - until ```TEST_SUITE_END``` is encountered (which internally calls ```TEST_SUITE("")``` with an empty string).

Does this explain the problem you are having? What part of the documentation would you recommend to be improved?

**Comment by FSund** [comment]
Seems like I didn't read the documentation properly, sorry for the confusion.

I definitely expected `TEST_SUITE` to behave the same way as `TEST_CASE`, when a body is appended. Seems like this, plus the fact that I got `TEST_SUITE` and `TEST_CASE` mixed up were cause for most of my errors.

I would suggest perhaps adding `TEST_SUITE_BEGIN()` to match `TEST_SUITE_END()`, and make `TEST_SUITE() {}` behave nicely with a body appended.
