### ISSUE TITLE
!!! BREAKING CHANGE !!! - Make TEST_SUITE work with blocks and add TEST_SUITE_BEGIN

### ISSUE THREAD

**Issue by FSund** [onqtam/doctest#41]
I think making the following code valid would be a good idea

```c++
TEST_SUITE("math")
{
    TEST_CASE("") {} // part of the math test suite
}
```

and adding the macro/typedef `TEST_SUITE_BEGIN`, to match `TEST_SUITE_END`

```c++
TEST_SUITE_BEGIN("gui")

TEST_CASE("") {} // part of the gui test suite

TEST_SUITE_END();
```

**Comment by onqtam** [comment]
having ```_BEGIN``` in the macro name would have been the right choice indeed... but this would be a breaking change.

For allowing test suites to have bodies and test cases inside them - not sure how that could be implemented - but one thing is for sure - the ```TEST_CASE``` macro won't be usable in that context - there will have to be a separate macro - like ```TEST_SUITE_CASE``` for cases inside a test suite block.

I'll have to think about these things...

**Comment by onqtam** [comment]
Actually this is possible! - see [UnitTest++](https://github.com/unittest-cpp/unittest-cpp/blob/master/tests/TestTestSuite.cpp#L6)

So now I'm considering it... However there are 2 drawbacks:

- changing the meaning of ```TEST_SUITE``` is a breaking change
- the name passed to ```TEST_SUITE``` will no longer be a string literal so it can get used as part of a namespace - see [here](https://github.com/unittest-cpp/unittest-cpp/blob/master/UnitTest%2B%2B/TestMacros.h#L19)

I don't think test suites are used that much because I'd assume doctest still has a small user base and I'm willing to make a breaking change (and document it in the changelog as such) buuut the naming of test suites will be inconsistent - not being a C string...

**Comment by onqtam** [comment]
This is how test suites are used now:

```c++
TEST_CASE("") {} // not part of any test suite

TEST_SUITE("math") {
    TEST_CASE("") {} // part of the math test suite
    TEST_CASE("") {} // part of the math test suite
}

TEST_SUITE_BEGIN("utils");

TEST_CASE("") {} // part of the utils test suite

TEST_SUITE_END();

TEST_CASE("") {} // not part of any test suite
```

**Comment by FSund** [comment]
I don't mind the breaking change (which makes sense given that I'm the one who suggested this in the first place), and I don't think the string literal issue affects me. 

Actually I'm not even using `TEST_SUITE` at the moment, so perhaps I'm not the best judge on this matter. 

I still think the change to having a unified way of calling `TEST_SUITE` and `TEST_CASE` would be good though.

**Comment by onqtam** [comment]
I figured out how to circumvent the string literal issue - and even edited my comment from 2 hours ago.

This is already implemented in the dev branch! I too like the new unified way of calling ```TEST_SUITE``` and ```TEST_CASE``` - so thanks for the suggestion!

**Comment by FSund** [comment]
Sorry, I had the page open for a while before submitting my comment, so I didn't catch that.

Nice work!
