### ISSUE TITLE
Test runner thread initialization

### ISSUE THREAD

**Issue by HrvojeFER** [onqtam/doctest#435]
Hello!
I just have a couple of questions about concurrent environments.

I am using a library for which I have to run everything on a separate thread that needs initialization. However, in order to debug and test everything properly, I need to initialize the test runner thread as well.

My questions are:
Are all the test fixtures, test cases, and subcases run on the same thread?
Are they all run on the same thread from which we implement doctest with DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN?
The reason is that I could just run the thread initialization in my main doctest implementation and not worry about it later.

Thank you in advance!

### Extra information
* doctest version: **v2.4.1**
* Operating System: **Windows**
* Compiler+version: **Visual Studio Community 2019**

**Comment by onqtam** [comment]
> Are all the test fixtures, test cases, and subcases run on the same thread?

Yes, they are all ran from whichever thread `doctest::Context::run()` is called - sequentially.

> Are they all run on the same thread from which we implement doctest with DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN?

`DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN` just drags the implementation of the test runner into the respective translation unit in order to be compiled - the thread the tests will be running from is the one from which you call `doctest::Context::run()` on your doctest context.

FYI (perhaps unrelated): doctest supports asserts and logging [from multiple threads within a single test case](https://github.com/onqtam/doctest/blob/master/doc/markdown/faq.md#is-doctest-thread-aware).

Let me know if this helps!

**Comment by HrvojeFER** [comment]
This is exactly the information I was looking for.
Thank you for the reply and for the wonderful doctest library! 😄
