### ISSUE TITLE
compilation issue in MSVC when defining DOCTEST_THREAD_LOCAL to static

### ISSUE THREAD

**Issue by apanloco** [onqtam/doctest#458]
## Description
define DOCTEST_THREAD_LOCAL to static:

```
#define DOCTEST_THREAD_LOCAL static
#define DOCTEST_CONFIG_IMPLEMENT
#include <doctest/doctest.h>
```

### Steps to reproduce
build

### Extra information
* doctest version: **v2.4.4** (conan.io)
* Operating System: **Windows 10**
* Compiler+version: **Visual Studio Version 16.8.3**

The reason is this place
```
#ifdef DOCTEST_PLATFORM_WINDOWS
    struct DebugOutputWindowReporter : public ConsoleReporter
    {
        DOCTEST_THREAD_LOCAL static std::ostringstream oss;

        DebugOutputWindowReporter(const ContextOptions& co)
                : ConsoleReporter(co, oss) {}
```

where static is, probably by accident, put after DOCTEST_THREAD_LOCAL

in other places it looks like this:
```
    DOCTEST_THREAD_LOCAL std::ostringstream DebugOutputWindowReporter::oss;
```
or
```
    DOCTEST_THREAD_LOCAL std::ostringstream g_oss; // NOLINT(cert-err58-cpp)
```
etc...

but this particular case is DOCTEST_PLATFORM_WINDOWS-only.

thanks!

**Comment by onqtam** [comment]
The reason that thread local there is static is that it's a class member and in all other cases the thread locals are globals and thus they don't need static. If you want to simply not have thread locals because you don't have access to a fully conformant C++11 compiler or you won't be doing anything from multiple threads you can simply define `DOCTEST_THREAD_LOCAL` without giving it a value - you don't have to set it to `static`. Let me know if this helps.

**Comment by apanloco** [comment]
that works well for me
i got the inspiration from this commit: https://github.com/onqtam/doctest/commit/21f250457d1746affe8c5617320139bf304788c0
what would the difference be, anything i should keep in mind?

**Comment by onqtam** [comment]
there's another commit after the one you linked where I'm removing the `static` from the define - I guess I must have realized that I cannot simply set it to `static`

**Comment by apanloco** [comment]
thanks for the help!
