### ISSUE TITLE
Adding a bunch of REQUIRE/CHECK utilities

### ISSUE THREAD

**Issue by damageboy** [onqtam/doctest#487]
## Description
I'm encountering a bit of missing macro-ification in doctest, namely things like:
* `{REQUIRE,CHECK}_CSTR_{EQ,NE}()` - for C-like `char *` strings
* `{REQUIRE,CHECK}_{NOT,}_NULL()` - for quickly comparing something to nullptr

Is this something that may be of interest for doctest in the form of a PR, or do these sort of requests
normally end up as utility headers in the project I'm maintaining?

**Comment by jiridanek** [comment]
Hey,

regarding your first point, maybe you aren't aware of [the `DOCTEST_CONFIG_TREAT_CHAR_STAR_AS_STRING` #define](https://github.com/onqtam/doctest/blob/master/doc/markdown/configuration.md#doctest_config_treat_char_star_as_string). In C++ code, `char *` strings are not that frequent, and when testing C code, changing the behavior with the define worked well so far for me.

For the second point, why don't you want to do `REQUIRE(p != nullptr)`? Afaik one of the most significant API design goals of doctest is to have an universal assertion macro and then smartly evaluate the condition within as that allows using normal C++ condition syntax, instead of defining a suite of different assertion macros.

**Comment by damageboy** [comment]
Hey @jiridanek, you are absoloutely right about the `DOCTEST_CONFIG_TREAT_CHAR_STAR_AS_STRING` as being a right way to go for `char *` assertions, and I've actually started using this.

As for the `== nullptr` or `!= nullptr` I see you point, and this is mostly about having an easier way to port from an existing framework to doctest...

I guess I can close the issue and leave it at that...

**Comment by jiridanek** [comment]
If you write a specific macro for the nullptr check and it works, maybe share it here. There may be other people in need. I heard that there is a small wave of exodus from catch2 to doctest going on ;P

**Comment by chunhualiu** [comment]
> Hey,
> 
> regarding your first point, maybe you aren't aware of [the `DOCTEST_CONFIG_TREAT_CHAR_STAR_AS_STRING` #define](https://github.com/onqtam/doctest/blob/master/doc/markdown/configuration.md#doctest_config_treat_char_star_as_string). In C++ code, `char *` strings are not that frequent, and when testing C code, changing the behavior with the define worked well so far for me.
> 
> For the second point, why don't you want to do `REQUIRE(p != nullptr)`? Afaik one of the most significant API design goals of doctest is to have an universal assertion macro and then smartly evaluate the condition within as that allows using normal C++ condition syntax, instead of defining a suite of different assertion macros.

With VS2022, I got below errors:

```
1>***\include\doctest\doctest.h(1278,25): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>***\include\doctest\doctest.h(1278): message : see reference to class template instantiation 'doctest::detail::not_char_pointer<T>' being compiled
1>***\include\doctest\doctest.h(1279,13): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>***\include\doctest\doctest.h(1280,13): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
```

I changed _DOCTEST_CONSTEXPR_ to _DOCTEST_CONSTEXPR int_

Not sure if it's a correct fix.
