### ISSUE TITLE
Further improvements on compile time - disable inlining of functions used in asserts

### ISSUE THREAD

**Issue by onqtam** [onqtam/doctest#70]

**Comment by onqtam** [comment]
binary and fast asserts are almost 3-4 times faster to compile now!

**Comment by Trass3r** [comment]
> binary and fast asserts are almost 3-4 times faster to compile in release mode with MSVC! unfortunately not much effect for other compilers/configs

You should test with `-Zc:inline` to make msvc behave properly like other compilers.

**Comment by onqtam** [comment]
Well the thing about `-Zc:inline` is that it's a compiler option and doctest doesn't try to enforce anything build-system-related. I could make it an `INTERFACE` property of the doctest CMake target, but not sure if that's nice, + the goal is to be as optimal as possible for all use cases (even when users get the header with `wget`/`curl` - without the CMake target).

**Comment by Trass3r** [comment]
I know but it's not a good idea to _optimize_ for a single compiler's broken default mode that only exists for insane backwards compatibility with non-sense (and since C++11 non-conforming) code.
Also it's the default for the average user anyway: https://devblogs.microsoft.com/cppblog/feedback-making-zcinline-default-for-debugrelease-configs-in-14/
