### ISSUE TITLE
!!! BREAKING CHANGE !!! - remove the custom implementation of std::is_constructible and optionally use the <type_traits> header because of infinite template recursion issues with GCC

### ISSUE THREAD

**Issue by chambm** [onqtam/doctest#85]
## Description

Template depth exceeded on GCC 

Here is a repro:
http://coliru.stacked-crooked.com/a/be9f09a38e109b69

I pasted current doctest.h in there and tacked a test case at the end.

I found the bug working with GCC 4.8.4, so it's not the GCC version. What is that template metaprogramming for in the Approx class? Seems a bit overly complex.

### Extra information

* doctest version: **1.2.1**
* Compiler+version: **GCC 7.1.0**

**Comment by onqtam** [comment]
interestingly enough clang [has no trouble](https://wandbox.org/permlink/uLjllwarrQdBZW5y)...

I originally added the ```is_constructible``` type trait to [support strong typedefs](https://github.com/onqtam/doctest/issues/62) of ```double``` for ```doctest::Approx``` - and took the implementation from [here](http://stackoverflow.com/a/40443701/3162383) because using ```std::is_constructible``` would require including ```<type_traits>```...

I'm not sure how to proceed with this - it might be a gcc problem, but it is for sure a huge template mess...

**Comment by chambm** [comment]
It also works on MSVC 12 and later. At least Update 5. I've seen an internal compiler error with VC 12 update 1 but couldn't figure out how to reproduce it. Been wondering whether it was related to this.

**Comment by onqtam** [comment]
I'll probably address this next week by making a config option (off by default) to support strong typedefs of double for Approx which would trigger including ```<type_traits>``` and use ```std::is_constructible```

**Comment by chambm** [comment]
A good compromise!

**Comment by onqtam** [comment]
this is now in the dev branch - soon I'll release version 1.2.2 with this going into master.
