### ISSUE TITLE
[question] Why are SUBCASEs executed only once when within a function called multiple times?

### ISSUE THREAD

**Issue by andreaplanet** [onqtam/doctest#88]
## Description
SUBCASE's are executed only once if within a  function.
I missed the documentation where it is described.
### Steps to reproduce
```
void MyTestCase(int n)
{
	SUBCASE("") { cout << "MyTestCase:" << n << endl; }
}


TEST_CASE("lots of nested subcases") {
	cout << endl << "root" << endl;
	MyTestCase(1);
	MyTestCase(2);
}
```

Expected output:
```
root
MyTestCase:1
MyTestCase:2
```

Got output:
```
root
MyTestCase:1
``` 

### Extra information
* doctest version: **1.2.1**
* Operating System: **Ubuntu 17.04 64 bit**
* Compiler+version: **g++ (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406**

and

* Operating System: **Windows 10**
* Compiler+version: **Visual Studio 2017 Community Edition**

**Comment by onqtam** [comment]
Hi!

This is the expected behavior. Doctest cannot (easily) know from what callstack a subcase is defined - from the point of view of the framework there is only one subcase found while executing the test case and it is uniquely identified by the file and line it is written at (using ```__FILE__``` and ```__LINE__```) and by its name.

What exactly is your testing scenario? Perhaps the subcases can be extracted from the separate function?

Perhaps I should improve the documentation :)
